// Generated by CoffeeScript 1.6.3
(function() {
  window.RoutineTimer = (function() {
    function RoutineTimer() {
      this.$stopwatch = $('#example-7');
    }

    RoutineTimer.prototype.create = function() {
      var _this = this;
      return this.stopwatch = new window.Stopwatch({
        targetTime: 3000,
        atTarget: function() {
          _this.stopwatch.disable();
          return _this.$stopwatch.addClass('completed');
        }
      }, function(time) {
        var percentageStr;
        percentageStr = "" + (Math.floor(time.progress * 100)) + "%";
        _this.$stopwatch.find('.inner.bar').css('width', percentageStr);
        return _this.$stopwatch.find('.percentage').text(percentageStr);
      });
    };

    RoutineTimer.prototype.initButtons = function() {
      var _this = this;
      this.$stopwatch.find('.start').click(function() {
        return _this.stopwatch.start();
      });
      this.$stopwatch.find('.stop').click(function() {
        return _this.stopwatch.stop();
      });
      return this.$stopwatch.find('.reset').click(function() {
        _this.stopwatch.enable();
        _this.$stopwatch.removeClass('completed');
        return _this.stopwatch.reset();
      });
    };

    RoutineTimer.prototype.init = function() {
      this.create();
      return this.initButtons();
    };

    return RoutineTimer;

  })();

}).call(this);
